Removed master_uri, added rmw, cyclonedds_config, and fastrtps_config
clearpathrobotics/robot_upstart pull request #112
Opened 2022-04-20 16:41 UTC by roni-kreinin

Allows DDS configuration in ROS2

2022-04-20 16:43 UTC, roni-kreinin commented
Example usage:

`ros2 run robot_upstart install turtlebot4_bringup/launch/joy_teleop.launch.py --job joy_teleop --rmw rmw_cyclonedds_cpp --cyclonedds_config "'<CycloneDDS><Domain><General><NetworkInterfaceAddress>wlp0s20f3</></></></>'"`

2022-04-20 19:31 UTC, tonybaltovski commented on robot_upstart/install_script.py
> +    p.add_argument("--fastrtps_config", type=str,
Could `--fastrtps_config` and `--cyclonedds_config` be merged into one variable?

2022-04-21 16:59 UTC, tonybaltovski requested changes

2022-04-21 16:59 UTC, tonybaltovski commented on templates/job-start.em
> +
Minor nit, whitespace

2022-04-21 18:06 UTC, tonybaltovski approved these changes

2022-04-21 18:06 UTC, merged