Melodic compatibility: rewrite getifip to make use of iproute2
clearpathrobotics/robot_upstart pull request #83
Opened 2019-06-13 11:13 UTC by Rayman

ifconfig is deprecated in favor of iproute2. So I rewrote the script to parse the json output of the `ip route addr show <INTERFACE>` command.

This should also work for lower versions of ubuntu, but I did not test those.

2019-06-13 19:45 UTC, mikepurvis requested changes
Great, thanks for this contribution!

2019-06-13 19:45 UTC, mikepurvis commented on scripts/getifip
> +parser.add_argument('interface', help='an integer for the accumulator')
Please update these strings.

2019-06-13 19:45 UTC, mikepurvis commented on scripts/getifip
> -# Please send comments, questions, or patches to code@clearpathrobotics.com
Please leave the BSD notice here, but feel free to change the copyright to yourself.

2019-06-13 19:45 UTC, mikepurvis commented on scripts/getifip
> +output = subprocess.check_output(cmd)
I guess it's style, but I would avoid shlex here. Just list the five separate chunks in a list or tuple and avoid the concatenation as well.

2019-06-14 09:18 UTC, Rayman commented
Thanks you for the review. I've addressed all comments.

2019-06-14 17:05 UTC, mikepurvis commented on scripts/getifip
> +#         Copyright (c) 2090, RUVU, b.v.
2019?

2019-06-15 13:03 UTC, gavanderhoorn commented on scripts/getifip
> +#         Copyright (c) 2090, RUVU, b.v.
No this is from the future ;)

2019-06-17 08:01 UTC, Rayman commented on scripts/getifip
> +#         Copyright (c) 2090, RUVU, b.v.
Fixed this

2019-06-21 11:07 UTC, Rayman commented
This patch only seems to work on melodic because `iproute2` should support the -json option. Can you make a melodic-devel branch then I'll retarget my PR.

2019-09-23 14:36 UTC, mikepurvis commented
I'm not over the moon about needing a distro branch in this repo, just for this change. Would it be possible to support both? Like, perhaps by testing for `ip addr` supporting the `-json` flag, and if not, falling back on the other `ifconfig` invocation?

2019-09-23 16:59 UTC, Rayman commented
I've done another try with this PR: https://github.com/clearpathrobotics/robot_upstart/pull/88. This keeps a single branch for all distros.

2019-10-09 19:29 UTC, closed without merging